AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

require:
  - ./lib/rubocop/cop/file_annotate/first_line_comment.rb

FileAnnotate/FirstLineComment:
  Enabled: true
  EnforcedStyle: forbidden # default is 'required', can be 'forbidden'
