AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/AsciiComments:
  Enabled: false

require:
  - file_annotate/rubocop

FileAnnotate/FirstLineComment:
  Enabled: true